import json
import logging

import pytest
from fastapi.testclient import TestClient

from api.main import app

client = TestClient(app, raise_server_exceptions=False)


def test_json_logging_middleware(caplog: pytest.LogCaptureFixture) -> None:
    # Arrange: Set logging level to capture INFO messages emitted during the request.
    caplog.set_level(logging.INFO)

    # Act: Perform a request to health check endpoint
    response = client.get("/health")
    assert response.status_code == 200

    # Assert: Parse JSON logs from stdout captured by the pytest caplog fixture.
    json_logs = []
    for record in caplog.records:
        try:
            log_data = json.loads(record.message)
            # Find the specific log entry generated by the StructuredLoggingMiddleware.
            if "path" in log_data and log_data["path"] == "/health":
                json_logs.append(log_data)
        except json.JSONDecodeError:
            continue

    # Verify that the middleware logged exactly one JSON record for this request.
    assert len(json_logs) == 1
    log = json_logs[0]

    # Assert JSON payload fields conform to the structured logging schema layout.
    assert log["method"] == "GET"
    assert log["path"] == "/health"
    assert log["status_code"] == 200
    assert "latency_ms" in log
    assert isinstance(log["latency_ms"], float)
    assert log["latency_ms"] >= 0.0
    assert "timestamp" in log
